version: "3.8"
services:
  db:
      build:
        context: ./db
        args:
          - MONGO_INITDB_ROOT_USERNAME=${MONGO_INITDB_ROOT_USERNAME}
          - MONGO_INITDB_ROOT_PASSWORD=${MONGO_INITDB_ROOT_PASSWORD}
      restart: always
      volumes:
        - blog-api-volume:/data/db
        - ./db/init/mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro 
      ports:
        - "27017:27017"     
  func:
      build: 
        context: ./functions/Blog.Function.API
      ports: 
        - "7132:80"
      depends_on:
        - db
volumes:
  blog-api-volume: