version: "3.8"
services:
  db:
      build:
        context: ./db
      restart: always
      volumes:
        - blog-api-volume:/data/db
      ports:
        - "27017:27017"
      environment:
        - MONGO_INITDB_ROOT_USERNAME=${MONGO_INITDB_ROOT_USERNAME}
        - MONGO_INITDB_ROOT_PASSWORD=${MONGO_INITDB_ROOT_PASSWORD}
        - MONGO_INITDB_DB_NAME=root-db
  func:
      build: 
        context: ./functions/Blog.Function.API
      ports: 
        - "7132:80"
      depends_on:
        - db
volumes:
  blog-api-volume: